import { Grantee } from './grantee';
import { Poc } from './poc';
import { Organization } from './organization';

export class ApplicationForm {

    constructor(
        public grantType: string,
        public organizationName: string,
        public address: string,
        public state: string,
        public applicationType: string,
        public congressionalDistrict: string,
        public projectTitle: string,
        public projectNumber: string,
        public projectYear: number,
        public submissionDate: string,
        public grantValue: number,
        public notificationsFrequency: string
    ) { }

    // public context: string,
    //     public userRole: string,
    //     public applicationId: string,
    //     public applicationNumber: string,
    //     public applicant: string,
    //     public amount: string,
    //     public fiscalYear: string,
    //     public programId: string,
    //     public status: string,
    //     public grantType: string,
    //     public grantee1: Grantee,
    //     public grantee2: Grantee,
    //     public organization: Organization,
    //     public poc: string,
    //     public pointOfContact: Poc,
    //     public subGrantee: string,
    //     public subGrantee1: Grantee,
    //     public subGrantee2: Grantee

    // {
    //     context: context-123-addform, 
    //     userRole:userRole-1, 
    //     applicationId: , 
    //     applicationNumber: 0, 
    //     applicant: Lisa Simpson, 
    //     amount:654321.12, 
    //     fiscalYear: 2017, 
    //     programId: 1, 
    //     status: Submitted, 
    //     grantType: FloodRecoveryGrant, 
    //     grantee1: { 
    //         address1: 123 Main Grant Street, 
    //         address2: Suite 100, 
    //         applicantType: Simple Applicant Type, 
    //         city: Los Angeles, 
    //         dunsID: DUNS-123-A, 
    //         finReportDate: 2016-12-31, 
    //         firstName: Miles, id: , 
    //         lastName: Synkovic, 
    //         state: California, 
    //         taxID: TAXID-098-ABC }, 
    //     grantee2: { 
    //         address1: 101 North Avenue, 
    //         address2: Floor 5000,
    //          applicantType: Slim Applicant Type, 
    //          city: New York, 
    //          dunsID: DUNS-999-01A, 
    //          finReportDate: 2016-12-29, 
    //          firstName: Tommy, 
    //          id: , 
    //          lastName: 
    //          Strollalini, 
    //          state: New York, 
    //          taxID: TAXID-999-ZZZ }, 
    //     organization: { 
    //         address1: 4321 East Park Boulevard, 
    //         applicationType: Bulk Applicant Type, 
    //         district: Green Light District, 
    //         name: Rescue Rangers, 
    //         organizationId: , 
    //         phoneNumber: 555-555-1234, 
    //         projectNumber: 1, 
    //         projectTitle: Big Project, 
    //         projectYear: 2017, 
    //         state: Maine }, 
    //     poc: Mama Mia, 
    //     pointOfContact: { 
    //         address1: 1 Rainbow Curve, 
    //         address2: , 
    //         city: Houston, 
    //         email: jess@bighelp.com, 
    //         firstName: Jess, 
    //         id: , 
    //         lastName: Tyme, 
    //         middleInitial: N, 
    //         organization: Big Help, 
    //         phone: 604-392-5839, 
    //         state: Texas, 
    //         title: CEO, 
    //         zip: 59423 }, 
    //     subGrantee: Joe Subway, 
    //     subGrantee1: { 
    //         address1: 48 Second Street, 
    //         address2: Apt 3, 
    //         applicantType: sub applicant type, 
    //         city: Newark, 
    //         dunsID: DUNS-847-YS, 
    //         finReportDate: 2016-12-20, 
    //         firstName: Tony, 
    //         id: , 
    //         lastName: Gotcha, 
    //         state: New Jersey, 
    //         taxID: TAXID-43-43-A }, 
    //     subGrantee2: { 
    //         address1: 48 Second Street, 
    //         address2: Apt 4, 
    //         applicantType: sub applicant type, 
    //         city: Newark, 
    //         dunsID: DUNS-847-YS, 
    //         finReportDate: 2016-12-20, 
    //         firstName: Shikara, 
    //         id: , 
    //         lastName: Ahlot, 
    //         state: New Jersey, 
    //         taxID: TAXID-43-43-B } 
    //     }
}